/*
 * Generated by gen_mascot.py (charge_glyph) - do not edit by hand.
 * 8x9 1-bit lightning bolt drawn inside the battery icon while charging.
 *
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t charge_glyph_map[] = {
#if CONFIG_NICE_VIEW_BESIM_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        0xfb, 0xf3, 0xe7, 0xe0, 0xc1, 0x83, 0xf3, 0xe7, 0xef,
};

const lv_image_dsc_t charge_glyph = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_I1,
    .header.flags = 0,
    .header.w = 8,
    .header.h = 9,
    .header.stride = 1,
    .data_size = 17,
    .data = charge_glyph_map,
};
